apiVersion: v1
kind: Service
metadata:
  name: microservicio-saludo
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: microservicio-saludo
  type: ClusterIP